sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sariamirza/react-docker .

script:
  - docker run --name test-c1 sariamirza/react-docker npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-container"
  env: "Multi-container-env"
  bucket_name: "elasticbeanstalk-eu-north-1-058264168537"
  bucket_path: "multi-container"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"