sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sariamirza/react-docker .

script:
  - docker run --name test-c1 sariamirza/react-docker npm run test -- --coverage --watchAll=false