version: "3"
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: app/frontend
    container_name: app-frontend
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app